openapi: 3.0.0
info:
  title: Users
  version: 1.0.0
  description: This API provides endpoints to manage activities on an e-learning platform.
               It allows users to create, retrieve, update, and delete various learning activities such as
               courses, quizzes, assignments, discussions, and more. Authentication and user-related functionalities
               are also included to manage users enrolled in activities and their progress

tags:
  - name: Users
    description: Operations related to users
  - name: Registration
    description: Operations related to user registration

paths:
  /api/users:
    get:
      summary: (Get all users)
      description: Get users with the provided details
      tags:
        - Users
      security:
        - bearerAuth: [] 
      parameters:
        - name: role
          in: query
          description: Filter users by role
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: Limit the number of results
          required: false
          schema:
            type: integer
            format: int32
            default: 10
        - name: page
          in: query
          description: Page number for paginated results
          required: false
          schema:
            type: integer
            format: int32
            default: 1
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    username:
                      type: string
                    email:
                      type: string
            example: 
              - id: 1
                username: john_doe
                email: john@example.com
              - id: 2
                username: jane_smith
                email: jane@example.com
        '400':
          description: Bad request, validation error
        '404':
          description: Response not found
        '500':
          description: Internal server error
  /api/registration:
    post:
      summary: (Create user)
      description: Register user with required details
      tags:
        - Users
      security:
        - bearerAuth: [] 
      requestBody:
        description: User details to be provided for registration
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                fullname:
                  type: string
                gender:
                  type: string
                phone_number:
                  type: string
                email:
                  type: string
              required:
                - username
                - fullname
                - gender
                - phone_number
                - email
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    username:
                      type: string
                    email:
                      type: string
            example: 
              - id: 1
                username: john_doe
                email: john@example.com
              - id: 2
                username: jane_smith
                email: jane@example.com
        '400':
          description: Bad request, validation error
        '404':
          description: Response not found
        '500':
          description: Internal server error
 
